"""initial_schema

Revision ID: 23a7539b9d43
Revises: 
Create Date: 2026-06-09 17:54:20.927283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a7539b9d43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bet_log', 'match_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('bet_log', 'home_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('bet_log', 'away_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('bet_log', 'sport',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'football'"))
    op.alter_column('bet_log', 'bet_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('bet_log', 'stake',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('bet_log', 'odds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('bet_log', 'model_prob',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('bet_log', 'edge',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('bet_log', 'result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('bet_log', 'profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('bet_log', 'placed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('bet_log', 'settled_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('clv_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('clv_data', 'match_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('clv_data', 'bookmaker',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('clv_data', 'market',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('clv_data', 'opening_odds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clv_data', 'closing_odds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clv_data', 'clv',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('clv_data', 'captured_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('model_accuracy', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('model_accuracy', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('model_accuracy', 'target',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('model_accuracy', 'accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('model_accuracy', 'brier_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('model_accuracy', 'log_loss',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('model_accuracy', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index('idx_model_acc', 'model_accuracy', ['model_name', 'target'], unique=True)
    op.alter_column('odds_cache', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('odds_cache', 'sport_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('odds_cache', 'home_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('odds_cache', 'away_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('odds_cache', 'bookmaker',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('odds_cache', 'h2h_home',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'h2h_away',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'h2h_draw',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'total_over',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'total_under',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'total_point',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'spread_home',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'spread_point',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'commence_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('odds_cache', 'fetched_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('performance_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('performance_snapshots', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('performance_snapshots', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'equity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'drawdown_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'roi',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'win_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('predictions', 'match_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('predictions', 'sport',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('predictions', 'home_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('predictions', 'away_team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('predictions', 'commence_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('predictions', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('predictions', 'home_prob',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'away_prob',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'draw_prob',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'over_prob',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'under_prob',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'predicted_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'predicted_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('predictions', 'under_prob',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('predictions', 'over_prob',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('predictions', 'draw_prob',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('predictions', 'away_prob',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('predictions', 'home_prob',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('predictions', 'model_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('predictions', 'commence_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('predictions', 'away_team',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('predictions', 'home_team',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('predictions', 'sport',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('predictions', 'match_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('predictions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('performance_snapshots', 'win_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'roi',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'drawdown_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'equity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'balance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('performance_snapshots', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('performance_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('odds_cache', 'fetched_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds_cache', 'commence_time',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'spread_point',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'spread_home',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'total_point',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'total_under',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'total_over',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'h2h_draw',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'h2h_away',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'h2h_home',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'bookmaker',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('odds_cache', 'away_team',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds_cache', 'home_team',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds_cache', 'sport_key',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds_cache', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_model_acc', table_name='model_accuracy')
    op.alter_column('model_accuracy', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_accuracy', 'log_loss',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('model_accuracy', 'brier_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('model_accuracy', 'accuracy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('model_accuracy', 'target',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_accuracy', 'model_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('model_accuracy', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('clv_data', 'captured_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('clv_data', 'clv',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('clv_data', 'closing_odds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('clv_data', 'opening_odds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('clv_data', 'market',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clv_data', 'bookmaker',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clv_data', 'match_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('clv_data', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('bet_log', 'settled_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bet_log', 'placed_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bet_log', 'profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('bet_log', 'result',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bet_log', 'edge',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('bet_log', 'model_prob',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('bet_log', 'odds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('bet_log', 'stake',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('bet_log', 'bet_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bet_log', 'sport',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'football'"))
    op.alter_column('bet_log', 'away_team',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bet_log', 'home_team',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bet_log', 'match_key',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bet_log', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
